name: Publish on maven central

on:
  push:
    branches: [ nusicFork ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          server_id: ossrh
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          nexus_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          nexus_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          maven_profiles: release
          maven_args: -DskipTests